env:
  API_TOKEN: ${{ secrets.MY_API_TOKEN_SECRET }}
  TEST_SECTER: ${{ secrets.TEST_SECTER_SECRET }}
name: test-pipeline
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
      - name: echo message
        run: echo Building the app...
      - name: sh
        shell: bash
        run: echo build complete
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
      - name: echo message
        run: echo Running unit tests...
      - name: sh
        shell: bash
        run: echo all tests passed
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
      - name: echo message
        run: echo Deploying app...
      - name: sh
        shell: bash
        run: echo deployed successfully
  Post-Build:
    if: always()
    name: Post Build
    runs-on: ubuntu-latest
    needs:
      - Build
      - Test
      - Deploy
    steps:
      - name: snapshot post build workflow status
        run: |-
          echo "success=${{ contains(needs.*.result,'success') && !contains(needs.*.result,'cancelled') && !contains(needs.*.result,'failure') }}" >> $GITHUB_OUTPUT
          echo "failure=${{ contains(needs.*.result,'failure') && !contains(needs.*.result,'cancelled') }}" >> $GITHUB_OUTPUT
        id: post_build
      - name: echo message
        run: echo test-pipeline failed!
        if: steps.post_build.outputs.failure == 'true'
      - name: echo message
        run: echo test-pipeline succeeded!
        if: steps.post_build.outputs.success == 'true'
